services:
  flask_web_server:
    build:
      context: .
      dockerfile: flask.Dockerfile
    container_name: flask_web_server
    restart: always
    ports:
      - "80:5000"
    volumes:
      - .:/app

  demo_ngrok:
    image: ngrok/ngrok
    container_name: demo_ngrok
    depends_on:
      - flask_web_server
    restart: always
    environment:
      - NGROK_AUTHTOKEN=2zf*************************Z4eZHF7zmvr
    ports:
      - "54088:4040"
    links:
      - flask_web_server:http
    command: http flask_web_server:5000
